site_name: Viterbo MSc Project (PyTorch Migration)
repo_url: https://github.com/JoernStoehler/msc-math-viterbo
theme:
  name: material
  language: en

strict: true

plugins:
  - search

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true

nav:
  - Charter: charter.md
  - Home: README.md
  - Reviews: reviews/README.md
  - Architecture: architecture/overview.md
  - Math API:
      - Overview: math/index.md
      - polytope: math/polytope.md
      - constructions: math/constructions.md
      - volume: math/volume.md
      - symplectic: math/symplectic.md
      - capacity_ehz: math/capacity_ehz.md
      - oriented_edge_spectrum_4d: math/oriented_edge_spectrum_4d.md
      - cstar_constant_spec: math/cstar_constant_spec.md
      - similarity: math/similarity.md
      - polar: math/polar.md
